## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers, Input

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [38]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df

Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [4]:
# Create a list of at least 10 column names to use as X data
x_columns_list = ['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime', 'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion']

# Create X_df using your selected columns
X_df = attrition_df[x_columns_list]

# Show the data types for X_df
X_df.dtypes

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
dtype: object

In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=68)

In [39]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

# Create a LabelEncoder instance
label_encoder = LabelEncoder()

# Fit and transform the OverTime column in the training set
X_train['OverTime'] = label_encoder.fit_transform(X_train['OverTime'])

# Transform the OverTime column in the testing set
X_test['OverTime'] = label_encoder.transform(X_test['OverTime'])

# Verify data type changes
print(X_train['OverTime'])
print(X_test['OverTime'])

216     0
413     0
1179    0
1067    1
445     0
       ..
236     0
202     1
932     1
1447    0
831     0
Name: OverTime, Length: 1102, dtype: int64
937     1
1329    0
1169    0
837     0
1305    0
       ..
633     0
938     0
995     1
67      0
1079    0
Name: OverTime, Length: 368, dtype: int64


In [7]:
over_time_counts = X_train['OverTime'].value_counts()
over_time_counts

OverTime
0    784
1    318
Name: count, dtype: int64

In [8]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')


# Fit the encoder to the training data
dept_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded  = dept_encoder.transform(y_train[['Department']])
y_test_dept_encoded = dept_encoder.transform(y_test[['Department']])

print(y_train_dept_encoded)
print(y_test_dept_encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [12]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")


# Fit the encoder to the training data
attrition_encoder.fit(y_train[['Attrition']])


# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition_encoded  = attrition_encoder.transform(y_train[['Attrition']])
y_test_attrition_encoded = attrition_encoder.transform(y_test[['Attrition']])

print(y_train_attrition_encoded)

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]


## Part 2: Create, Compile, and Train the Model

In [14]:
# Find the number of columns in the X training data.
X_columns = len(X_train_scaled[0])
X_columns
# Create the input layer
input_layer = Input(shape=(X_columns,), name='input')
# # Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu', name='shared1')(input_layer)
shared_layer2 = layers.Dense(128, activation='relu', name='shared2')(shared_layer1)


In [16]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden = layers.Dense(32, activation='relu', name='department_hidden')(shared_layer2)

# Create the output layer
dept_output = layers.Dense(y_train_dept_encoded.shape[1], activation='softmax', name='department_output')(dept_hidden)

In [17]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(32, activation='relu', name='attrition_hidden')(shared_layer2)

# Create the output layer
attrition_output = layers.Dense(y_train_attrition_encoded.shape[1], activation='sigmoid', name='attrition_output')(attrition_hidden)

In [18]:
# Create the model
model = Model(inputs=input_layer, outputs={'department_output': dept_output, 'attrition_output': attrition_output})

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'},
              metrics={'department_output': 'accuracy', 'attrition_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)        │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared1 (Dense)           │ (None, 64)             │            704 │ input[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared2 (Dense)           │ (None, 128)            │          8,320 │ shared1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden (Dense)  │ (None, 32)             │          4,128 │ shared2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden (Dense) │ (None, 32)             │          4,128 │ shared2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             66 │ attrition_hidden[0][0] │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             99 │ department_hidden[0][… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
# Train the model
model.fit(
    X_train_scaled,
    {'department_output': y_train_dept_encoded, 'attrition_output': y_train_attrition_encoded},
    epochs=100,
    batch_size=25,
    validation_split=0.2
)

Epoch 1/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 1.0000 - attrition_output_loss: 6.7495e-04 - department_output_accuracy: 0.9950 - department_output_loss: 0.0144 - loss: 0.0151 - val_attrition_output_accuracy: 0.7828 - val_attrition_output_loss: 2.8327 - val_department_output_accuracy: 0.5430 - val_department_output_loss: 4.5171 - val_loss: 7.2489
Epoch 2/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 1.0000 - attrition_output_loss: 9.4196e-04 - department_output_accuracy: 0.9805 - department_output_loss: 0.0814 - loss: 0.0825 - val_attrition_output_accuracy: 0.7828 - val_attrition_output_loss: 2.8381 - val_department_output_accuracy: 0.5566 - val_department_output_loss: 4.4914 - val_loss: 7.2389
Epoch 3/100
36/36 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - attrition_output_accuracy: 0.9990 - attrition_output_loss: 0.0038 - department_output_accuracy: 0.9678 - department_output_loss: 0.0844 - loss: 0.0883 - val_attrition_output_accuracy: 

In [36]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'department_output': y_test_dept_encoded, 'attrition_output': y_test_attrition_encoded})
test_results

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8184 - attrition_output_loss: 2.9389 - department_output_accuracy: 0.5075 - department_output_loss: 5.3259 - loss: 8.2485  


[8.295485496520996,
 4.986288070678711,
 3.414893388748169,
 0.7989130616188049,
 0.5244565010070801]

In [37]:
# Print the accuracy for both department and attrition

print(f"Department predictions accuracy: {test_results[3]}")
print(f"Attrition predictions accuracy: {test_results[4]}")

Department predictions accuracy: 0.7989130616188049
Attrition predictions accuracy: 0.5244565010070801


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy can be a decent metric, but it may not be for this dataset, considering if there is an imbalance in the classes, especially if there is an imbalance between the classes for example, if the number of employees who leave is much lower than those who remain with the company. In these situations, other metrics like F1 score, precision, and recall can maybe provide a better understanding of the model's performance, especially for the minority class, in this case attrition. These metrics can also help with understanding if the model is identifying true positives and minimizing false negatives.
2. The softmax activation function is good for the department output layer because it works well for problems with multi-class classification, which gives output probabilities for every class. For the attrition output layer, the sigmoid activation function is good because it works well for binary classification problems, providing a probability of company retention - whether the employee will stay with the job or leave.
3. There are a fews to improve the model, such as hyperparameter tuning - so changing the number of layers, neurons and different activation functions.
More data could also be collected to augment the dataset and train the model on a larger dataset. When choosing the X columns, I only chose 10 and there are various other columns to choose from, so I could have used different combinations of the columns, plus more columns.
